server:
  port: 3000


spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      notify-ending: notify-ending
    consumer:
      group-id: order-group
      auto-offset-reset: latest
  data:
    mongodb:
      database: orders
      uri: ${MONGO_DB_URL:mongodb://admin:1234567@localhost:27017}


logging:
  level:
    org:
      apache:
        kaflaa: OFF